# Antes se ponia la version del formato de Docker Compose
#version: '3.8'

# Definición de los servicios para la app (MongoDB y el servidor gRPC)
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_peces
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  grpc_server:
    # Usa el Dockerfile para construir la imagen del servidor gRPC
    build: .
    container_name: grpc_server_peces
    # Puerto para gRPC que se usara en Postman
    ports:
      - "50051:50051" 
    depends_on:
      - mongodb
    # Espejea el codigo fuente al contenedor
    volumes:
      - .:/app    

# Volumen que almacena los datos de MongoDB incluso si el contenedor se detiene o elimina
volumes:
  mongo_data: